/**
 * Diff Proposal Generator - Step 15
 * Generates candidate patches for edit stage
 * V1: Deterministic/template-based (no LLM required yet)
 */

import { FileDiff } from './diffManager';

export interface DiffProposalInput {
  userIntent: string;
  planSteps: Array<{ description: string }>;
  retrievalResults?: Array<{ file_path: string; excerpt: string }>;
}

export interface DiffProposalOutput {
  description: string;
  diffs: FileDiff[];
  filesChanged: string[];
  changeIntent: string;
  riskLevel: 'low' | 'medium' | 'high';
  rationale: string[];
}

/**
 * Generate a diff proposal based on intent, plan, and retrieval results
 * V1 Implementation: Creates a deterministic placeholder diff for testing
 */
export function generateDiffProposal(input: DiffProposalInput): DiffProposalOutput {
  const { userIntent, planSteps } = input;

  // V1: Generate a deterministic placeholder diff
  // Creates a new file in docs/ directory to demonstrate the full pipeline
  const targetPath = 'docs/ordinex_proposal.md';
  
  // Generate content based on user intent and plan
  const proposalContent = generateProposalDocument(userIntent, planSteps);
  
  // Create a unified diff
  const diff: FileDiff = {
    file_path: targetPath,
    operation: 'create',
    new_content: proposalContent,
    patch: generateUnifiedDiffPatch('', proposalContent, targetPath)
  };

  return {
    description: `Proposal document based on: "${userIntent.substring(0, 50)}..."`,
    diffs: [diff],
    filesChanged: [targetPath],
    changeIntent: 'Create proposal document capturing intent and planned changes',
    riskLevel: 'low',
    rationale: [
      'Creates new file in docs/ directory (safe location)',
      'No modifications to existing code',
      'Demonstrates full diff proposal pipeline',
      'Based on user intent and generated plan'
    ]
  };
}

/**
 * Generate proposal document content
 */
function generateProposalDocument(userIntent: string, planSteps: Array<{ description: string }>): string {
  const timestamp = new Date().toISOString();
  
  const stepsText = planSteps
    .map((step, idx) => `${idx + 1}. ${step.description}`)
    .join('\n');

  return `# Ordinex Proposal Document

**Generated**: ${timestamp}

## User Intent

${userIntent}

## Planned Approach

${stepsText}

## Status

This proposal document was generated by Ordinex Step 15 (Edit Stage - Propose Diff).

The proposed changes are based on the user's intent and the generated plan.
This demonstrates the diff proposal pipeline without requiring LLM integration.

## Next Steps

- Review this proposal
- Click "View Diff" to see the proposed changes
- Click "Request Apply" to proceed with applying the diff
- The system will request approval before making any actual changes

---

*This is a V1 deterministic placeholder. Future versions will use LLM-powered diff generation.*
`;
}

/**
 * Generate unified diff patch format
 */
function generateUnifiedDiffPatch(oldContent: string, newContent: string, filePath: string): string {
  const newLines = newContent.split('\n');
  const lineCount = newLines.length;

  const patchLines: string[] = [];
  patchLines.push(`--- /dev/null`);
  patchLines.push(`+++ ${filePath}`);
  patchLines.push(`@@ -0,0 +1,${lineCount} @@`);
  
  newLines.forEach(line => {
    patchLines.push(`+${line}`);
  });

  return patchLines.join('\n');
}

/**
 * Check if a file path is within scope
 */
export function isFileInScope(filePath: string, scopeFiles: string[]): boolean {
  // If scope is empty, consider everything in scope (for initial development)
  if (scopeFiles.length === 0) {
    return true;
  }
  
  return scopeFiles.some(scopedFile => {
    return filePath === scopedFile || filePath.startsWith(scopedFile + '/');
  });
}

/**
 * Validate diff proposal against scope constraints
 */
export function validateDiffAgainstScope(
  diffs: FileDiff[],
  scopeFiles: string[]
): { valid: boolean; outOfScopeFiles: string[] } {
  const outOfScopeFiles = diffs
    .map(d => d.file_path)
    .filter(path => !isFileInScope(path, scopeFiles));

  return {
    valid: outOfScopeFiles.length === 0,
    outOfScopeFiles
  };
}
