/**
 * Design Pack Data Model Tests
 * 
 * Tests the design pack data structure and remaining utility functions.
 * The old designPackSelector.ts (deterministic selection, vibe guardrails)
 * has been removed — design tokens are now generated by styleIntentResolver.
 */

import { describe, test, expect } from 'vitest';

import {
  DESIGN_PACKS,
  getDesignPackById,
  getDefaultPacksForPicker,
  formatTokensSummary,
} from '../scaffold/designPacks';

describe('DESIGN_PACKS', () => {
  test('should have exactly 12 packs', () => {
    expect(DESIGN_PACKS.length).toBe(12);
  });

  test('all packs should have required fields', () => {
    for (const pack of DESIGN_PACKS) {
      expect(pack.id).toBeTruthy();
      expect(pack.name).toBeTruthy();
      expect(pack.vibe).toBeTruthy();
      expect(pack.tokens).toBeDefined();
      expect(pack.tokens.colors).toBeDefined();
      expect(pack.tokens.fonts).toBeDefined();
      expect(pack.preview).toBeDefined();
      expect(pack.preview.imageAssetId).toBeTruthy();
    }
  });

  test('all packs should have unique IDs', () => {
    const ids = DESIGN_PACKS.map(p => p.id);
    const uniqueIds = new Set(ids);
    expect(uniqueIds.size).toBe(DESIGN_PACKS.length);
  });

  test('all packs should have valid color tokens', () => {
    for (const pack of DESIGN_PACKS) {
      const { colors } = pack.tokens;
      expect(colors.primary).toBeTruthy();
      expect(colors.secondary).toBeTruthy();
      expect(colors.accent).toBeTruthy();
      expect(colors.background).toBeTruthy();
      expect(colors.foreground).toBeTruthy();
      expect(colors.muted).toBeTruthy();
      expect(colors.border).toBeTruthy();
    }
  });
});

describe('getDesignPackById', () => {
  test('should return pack for valid ID', () => {
    const pack = getDesignPackById('minimal-light');
    expect(pack).toBeDefined();
    expect(pack?.id).toBe('minimal-light');
    expect(pack?.name).toBe('Minimal Light');
  });

  test('should return undefined for invalid ID', () => {
    const pack = getDesignPackById('nonexistent-pack');
    expect(pack).toBeUndefined();
  });
});

describe('getDefaultPacksForPicker', () => {
  test('should return max 6 packs', () => {
    const packs = getDefaultPacksForPicker();
    expect(packs.length).toBeLessThanOrEqual(6);
    expect(packs.length).toBeGreaterThan(0);
  });

  test('should include minimal-light as default', () => {
    const packs = getDefaultPacksForPicker();
    const hasMinimalLight = packs.some(p => p.id === 'minimal-light');
    expect(hasMinimalLight).toBe(true);
  });

  test('should have diverse vibes', () => {
    const packs = getDefaultPacksForPicker();
    const vibes = new Set(packs.map(p => p.vibe));
    expect(vibes.size).toBeGreaterThan(1);
  });
});

describe('formatTokensSummary', () => {
  test('should format tokens summary correctly', () => {
    const pack = getDesignPackById('minimal-light')!;
    const summary = formatTokensSummary(pack);
    expect(summary).toContain('Primary:');
    expect(summary).toContain('Font:');
    expect(summary).toContain(pack.tokens.colors.primary);
    expect(summary).toContain(pack.tokens.fonts.heading);
  });
});
